### ISSUE TITLE
Address Field layout edits don't stick

### ISSUE THREAD

**Issue by KatieMFritz** [doublesecretagency/craft-smartmap#36]
After creating and saving a new Address field, the sub fields go into the following order:
![screen shot 2019-03-05 at 10 49 09 am](https://user-images.githubusercontent.com/7085184/53796447-7842be00-3f34-11e9-9271-950135a4b74d.png)

If I change them and save the field, upon opening the field again, they're back to that default.

Local site info:
![screen shot 2019-03-05 at 10 50 49 am](https://user-images.githubusercontent.com/7085184/53796509-9f00f480-3f34-11e9-95e5-1cba92ffce33.png)
![screen shot 2019-03-05 at 10 50 55 am](https://user-images.githubusercontent.com/7085184/53796512-9f998b00-3f34-11e9-9903-1e074a7a27c0.png)

![screen shot 2019-03-05 at 10 51 38 am](https://user-images.githubusercontent.com/7085184/53796532-ac1de380-3f34-11e9-9a5b-d8ffc898b127.png)

**Comment by lindseydiloreto** [comment]
Hmm, interesting. My suspicion is that this has something to do with the `project.yaml` file.

Can you see if the field shows up in there? And if it does, can you grab a screenshot or snippet and post it here?

**Comment by KatieMFritz** [comment]
```yaml
  840ba690-e793-40bc-8c3b-538672264018:
    contentColumnType: string
    fieldGroup: fed981b0-3708-4ebb-b4a2-d1a1ed72a61c
    handle: testAddress
    instructions: ''
    name: 'Test Address'
    searchable: true
    settings:
      dragPinDefault: ''
      dragPinLatitude: '0'
      dragPinLongitude: '0'
      dragPinZoom: '4'
      layout:
        city:
          enable: 1
          width: 50
        country:
          enable: 1
          width: 100
        lat:
          enable: 1
          width: 50
        lng:
          enable: 1
          width: 50
        state:
          enable: 1
          width: 15
        street1:
          enable: 1
          width: 100
        street2:
          enable: 1
          width: 100
        zip:
          enable: 1
          width: 35
    translationKeyFormat: null
    translationMethod: none
    type: doublesecretagency\smartmap\fields\Address
```
